In [19]:
pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (4.15.0)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests) (2026.6.17)
Requirement already satisfied: soupsieve>=1.6.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/manimaranjb/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/manimaranjb/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [20]:
import requests
import pandas as pd

from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse

In [21]:
url = "https://www.guvi.in/"

response = requests.get(url, timeout=10)

print("Status Code:", response.status_code)

Status Code: 200

### Check the webpage

In [22]:
soup = BeautifulSoup(response.text, "html.parser")

print("Page Title:")
print(soup.title)

Page Title:
<title q:head="">HCL GUVI | Learn to code in your native language</title>

In [23]:
text = soup.get_text(separator=" ", strip=True)

print(text[:2000])

HCL GUVI | Learn to code in your native language Want to Earn IIM Indore Executive Alumni Status? AI + Product Management Campus Immersion Live Projects Register by 18 October Enroll Now Want to Earn IIM Indore Executive Alumni Status? Register by 18 October Enroll Now LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Still Confused? Request a Callback Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Login Sign up Login Sign up LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an

### Discover internal GUVI links.

In [24]:
links = []

for tag in soup.find_all("a", href=True):
    full_url = urljoin(url, tag["href"])
    links.append(full_url)

print("Total links found:", len(links))

Total links found: 141

In [25]:
# remove duplicates
links = list(set(links))

print("Unique links:", len(links))

Unique links: 75

In [26]:
# keep only GUVI links
guvi_links = []

for link in links:
    if "guvi.in" in urlparse(link).netloc:
        guvi_links.append(link)

print("GUVI internal links:", len(guvi_links))

GUVI internal links: 65

In [27]:
# display a sample
for link in guvi_links[:30]:
    print(link)

https://www.guvi.in/courses/project-management/jira-jira-project-management/
https://www.guvi.in/#courses
https://www.guvi.in/referral/
https://www.guvi.in/code-kata/
https://www.guvi.in/referral?utm_source=product_feature-onboarding_popup&utm_medium=referral_exploremore
https://www.guvi.in/zen-class/?prod_feature=Homepage-HeaderLiveClass-RequestCallback-ThankYouPopup
https://www.guvi.in/rewards/
https://www.guvi.in/courses/machine-learning-and-ai/claude-code/?prod_feature=pythonzerotohero_homepage
https://www.guvi.in/zen-class?utm_source=product_feature-onboarding_popup&utm_medium=zen_exploremore&prod_feature=Homepage-User-Roadmap-Loggedin
https://www.guvi.in/webkata/
https://app.guvi.in/?utm_source=guvi-website&utm_medium=home-page&utm_campaign=install-banner&utm_content=home&track=true
https://www.guvi.in/leader-board/
https://www.guvi.in/courses/tamil/programming/c-programming/
https://www.guvi.in/explore-all-courses/?price=free
https://www.guvi.in/guvi-affiliate/
https://www.guvi.in/#rewards
https://www.guvi.in/debugging/
https://www.guvi.in/courses/network-and-security/mobile-hacking/
https://www.guvi.in/free-resources/
https://www.guvi.in/courses/professional-development/product-management-interview-preparation/
https://www.guvi.in/explore-all-courses/?course_type=bundle
https://www.guvi.in/community/campus-ambassador/
https://www.guvi.in/terms-of-service/
https://www.guvi.in/hub/
https://www.guvi.in/skill-assessment/?prod_feature=Homepage-Free-Skill-Assessment
https://www.guvi.in/courses/business-and-management/sap-s4-hana/
https://www.guvi.in/zen-class/iim-indore-product-management/?prod_feature=HomePage%20-TopbannerStrip-IIM-PM
https://www.guvi.in/courses/business-and-management/introduction-to-esg/
https://www.guvi.in/#practicePlatform
https://www.guvi.in/courses/project-and-product-management/introduction-to-agile-and-project-management/

### Inspect the 65 GUVI links

In [28]:
for i, link in enumerate(guvi_links, start=1):
    print(i, link)

1 https://www.guvi.in/courses/project-management/jira-jira-project-management/
2 https://www.guvi.in/#courses
3 https://www.guvi.in/referral/
4 https://www.guvi.in/code-kata/
5 https://www.guvi.in/referral?utm_source=product_feature-onboarding_popup&utm_medium=referral_exploremore
6 https://www.guvi.in/zen-class/?prod_feature=Homepage-HeaderLiveClass-RequestCallback-ThankYouPopup
7 https://www.guvi.in/rewards/
8 https://www.guvi.in/courses/machine-learning-and-ai/claude-code/?prod_feature=pythonzerotohero_homepage
9 https://www.guvi.in/zen-class?utm_source=product_feature-onboarding_popup&utm_medium=zen_exploremore&prod_feature=Homepage-User-Roadmap-Loggedin
10 https://www.guvi.in/webkata/
11 https://app.guvi.in/?utm_source=guvi-website&utm_medium=home-page&utm_campaign=install-banner&utm_content=home&track=true
12 https://www.guvi.in/leader-board/
13 https://www.guvi.in/courses/tamil/programming/c-programming/
14 https://www.guvi.in/explore-all-courses/?price=free
15 https://www.guvi.in/guvi-affiliate/
16 https://www.guvi.in/#rewards
17 https://www.guvi.in/debugging/
18 https://www.guvi.in/courses/network-and-security/mobile-hacking/
19 https://www.guvi.in/free-resources/
20 https://www.guvi.in/courses/professional-development/product-management-interview-preparation/
21 https://www.guvi.in/explore-all-courses/?course_type=bundle
22 https://www.guvi.in/community/campus-ambassador/
23 https://www.guvi.in/terms-of-service/
24 https://www.guvi.in/hub/
25 https://www.guvi.in/skill-assessment/?prod_feature=Homepage-Free-Skill-Assessment
26 https://www.guvi.in/courses/business-and-management/sap-s4-hana/
27 https://www.guvi.in/zen-class/iim-indore-product-management/?prod_feature=HomePage%20-TopbannerStrip-IIM-PM
28 https://www.guvi.in/courses/business-and-management/introduction-to-esg/
29 https://www.guvi.in/#practicePlatform
30 https://www.guvi.in/courses/project-and-product-management/introduction-to-agile-and-project-management/
31 https://www.guvi.in/corporates/
32 https://www.guvi.in/courses/business-and-management/business-finance/
33 https://www.guvi.in/#profile
34 https://www.guvi.in/refund-policy/
35 https://www.guvi.in/faq/
36 https://www.guvi.in/contact/
37 https://www.guvi.in/courses/project-management/confluence/
38 https://www.guvi.in/courses/programming/java-programming/
39 https://www.guvi.in/rewards?utm_source=product_feature-onboarding_popup&utm_medium=rewards_exploremore
40 https://forum.guvi.in/session/sso
41 https://www.guvi.in/free-resume-builder/
42 https://www.guvi.in/sqlkata/
43 https://www.guvi.in/ide/
44 https://www.guvi.in/about/
45 https://www.guvi.in/courses/
46 https://www.guvi.in/#finish
47 https://www.guvi.in/#welcome
48 https://www.guvi.in/courses/web-development/angular-basics/
49 https://www.guvi.in/
50 https://www.guvi.in/#leaderBoard
51 https://www.guvi.in/community/hcl-guvi-industrial-campus-visit/
52 https://www.guvi.in/free-resources/
53 https://www.guvi.in/#liveClass
54 https://www.guvi.in/zen-class-review/?prod_feature=HomePage-SuccessStories
55 https://www.guvi.in/courses/personal-development/resume-building/
56 https://www.guvi.in/courses/programming/python/
57 https://www.guvi.in/courses/cloud-computing/aws-fundamentals/
58 https://www.guvi.in/courses/project-management/project-management-fundamentals/
59 https://www.guvi.in/explore-all-courses/?price=paid
60 https://www.guvi.in/#referral
61 https://www.guvi.in/privacy-policy/
62 https://www.guvi.in/courses/business-and-management/entrepreneurship-bootstrap-vs-fundraising/
63 https://www.guvi.in/courses/?current_tab=myCourses&utm_source=product_feature-onboarding_popup&utm_medium=courses_exploremore
64 https://www.guvi.in/courses/business-and-management/email-etiquette/
65 https://www.guvi.in/courses/security/introduction-to-dark-web/

### Clean the URLs

In [29]:
from urllib.parse import urljoin, urlparse, urlunparse

In [30]:
def clean_url(url):
    parsed = urlparse(url)

    clean = parsed._replace(
        query="",
        fragment=""
    )

    return urlunparse(clean)

In [31]:
cleaned_links = []

for link in guvi_links:
    link = clean_url(link)

    if link not in cleaned_links:
        cleaned_links.append(link)

print("Cleaned links:", len(cleaned_links))

Cleaned links: 53

### Exclude unwanted pages

In [32]:
exclude_keywords = [
    "session/sso",
    "privacy-policy",
    "terms-of-service"
]

In [33]:
filtered_links = []

for link in cleaned_links:

    if not any(
        keyword in link.lower()
        for keyword in exclude_keywords
    ):
        filtered_links.append(link)

print("Useful links:", len(filtered_links))

Useful links: 50

In [34]:
# Check the cleaned URLs
for i, link in enumerate(filtered_links, start=1):
    print(i, link)

1 https://www.guvi.in/courses/project-management/jira-jira-project-management/
2 https://www.guvi.in/
3 https://www.guvi.in/referral/
4 https://www.guvi.in/code-kata/
5 https://www.guvi.in/referral
6 https://www.guvi.in/zen-class/
7 https://www.guvi.in/rewards/
8 https://www.guvi.in/courses/machine-learning-and-ai/claude-code/
9 https://www.guvi.in/zen-class
10 https://www.guvi.in/webkata/
11 https://app.guvi.in/
12 https://www.guvi.in/leader-board/
13 https://www.guvi.in/courses/tamil/programming/c-programming/
14 https://www.guvi.in/explore-all-courses/
15 https://www.guvi.in/guvi-affiliate/
16 https://www.guvi.in/debugging/
17 https://www.guvi.in/courses/network-and-security/mobile-hacking/
18 https://www.guvi.in/free-resources/
19 https://www.guvi.in/courses/professional-development/product-management-interview-preparation/
20 https://www.guvi.in/community/campus-ambassador/
21 https://www.guvi.in/hub/
22 https://www.guvi.in/skill-assessment/
23 https://www.guvi.in/courses/business-and-management/sap-s4-hana/
24 https://www.guvi.in/zen-class/iim-indore-product-management/
25 https://www.guvi.in/courses/business-and-management/introduction-to-esg/
26 https://www.guvi.in/courses/project-and-product-management/introduction-to-agile-and-project-management/
27 https://www.guvi.in/corporates/
28 https://www.guvi.in/courses/business-and-management/business-finance/
29 https://www.guvi.in/refund-policy/
30 https://www.guvi.in/faq/
31 https://www.guvi.in/contact/
32 https://www.guvi.in/courses/project-management/confluence/
33 https://www.guvi.in/courses/programming/java-programming/
34 https://www.guvi.in/rewards
35 https://www.guvi.in/free-resume-builder/
36 https://www.guvi.in/sqlkata/
37 https://www.guvi.in/ide/
38 https://www.guvi.in/about/
39 https://www.guvi.in/courses/
40 https://www.guvi.in/courses/web-development/angular-basics/
41 https://www.guvi.in/community/hcl-guvi-industrial-campus-visit/
42 https://www.guvi.in/free-resources/
43 https://www.guvi.in/zen-class-review/
44 https://www.guvi.in/courses/personal-development/resume-building/
45 https://www.guvi.in/courses/programming/python/
46 https://www.guvi.in/courses/cloud-computing/aws-fundamentals/
47 https://www.guvi.in/courses/project-management/project-management-fundamentals/
48 https://www.guvi.in/courses/business-and-management/entrepreneurship-bootstrap-vs-fundraising/
49 https://www.guvi.in/courses/business-and-management/email-etiquette/
50 https://www.guvi.in/courses/security/introduction-to-dark-web/

### Categorize pages

In [35]:
def get_category(url):

    url = url.lower()

    if "/courses/" in url:
        return "Course"

    elif "/zen-class" in url:
        return "Live Program"

    elif "/faq" in url:
        return "FAQ"

    elif "/free-resources" in url:
        return "Resource"

    elif "/community/" in url:
        return "Community"

    elif "/code-kata" in url:
        return "Practice"

    elif "/webkata" in url:
        return "Practice"

    elif "/sqlkata" in url:
        return "Practice"

    elif "/skill-assessment" in url:
        return "Assessment"

    elif "/refund-policy" in url:
        return "Policy"

    elif "/about" in url:
        return "About"

    elif "/contact" in url:
        return "Contact"

    else:
        return "Other"

In [36]:
for link in filtered_links[:20]:
    print(get_category(link), "->", link)

Course -> https://www.guvi.in/courses/project-management/jira-jira-project-management/
Other -> https://www.guvi.in/
Other -> https://www.guvi.in/referral/
Practice -> https://www.guvi.in/code-kata/
Other -> https://www.guvi.in/referral
Live Program -> https://www.guvi.in/zen-class/
Other -> https://www.guvi.in/rewards/
Course -> https://www.guvi.in/courses/machine-learning-and-ai/claude-code/
Live Program -> https://www.guvi.in/zen-class
Practice -> https://www.guvi.in/webkata/
Other -> https://app.guvi.in/
Other -> https://www.guvi.in/leader-board/
Course -> https://www.guvi.in/courses/tamil/programming/c-programming/
Other -> https://www.guvi.in/explore-all-courses/
Other -> https://www.guvi.in/guvi-affiliate/
Other -> https://www.guvi.in/debugging/
Course -> https://www.guvi.in/courses/network-and-security/mobile-hacking/
Resource -> https://www.guvi.in/free-resources/
Course -> https://www.guvi.in/courses/professional-development/product-management-interview-preparation/
Community -> https://www.guvi.in/community/campus-ambassador/

### Create the page scraping function

In [37]:
def scrape_page(url):
    try:
        response = requests.get(
            url,
            timeout=10
        )

        if response.status_code != 200:
            return None

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # Remove unnecessary HTML elements
        for tag in soup([
            "script",
            "style",
            "noscript"
        ]):
            tag.decompose()

        title = (
            soup.title.get_text(strip=True)
            if soup.title
            else ""
        )

        content = soup.get_text(
            separator=" ",
            strip=True
        )

        return {
            "url": url,
            "title": title,
            "category": get_category(url),
            "content": content
        }

    except requests.RequestException as error:
        print(f"Error scraping {url}: {error}")
        return None

In [38]:
# Test only 5 pages

test_links = filtered_links[:5]

test_data = []

for link in test_links:

    result = scrape_page(link)

    if result:
        test_data.append(result)

In [39]:
test_df = pd.DataFrame(test_data)

test_df[["category", "title", "url"]]

,category,title,url
0,Course,Best Jira: Jira project management Course Onli...,https://www.guvi.in/courses/project-management...
1,Other,HCL GUVI | Learn to code in your native language,https://www.guvi.in/
2,Other,Referral | HCL GUVI,https://www.guvi.in/referral/
3,Practice,HCL GUVI | Learn to code in your native language,https://www.guvi.in/code-kata/
4,Other,Referral | HCL GUVI,https://www.guvi.in/referral

In [40]:
test_df.shape

(5, 4)

In [41]:
# check the actual text

print(test_df.iloc[0]["content"][:2000])

Best Jira: Jira project management Course Online with Certification | GUVI LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Still Confused? Request a Callback Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Login Sign up Login Sign up LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Pre

In [42]:
# Create a simple cleaning function

import re

def clean_text(text):
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)

    # Remove repeated spaces around punctuation
    text = re.sub(r"\s+([.,!?;:])", r"\1", text)

    # Remove leading/trailing spaces
    text = text.strip()

    return text

In [43]:
sample_text = test_df.iloc[0]["content"]

cleaned_sample = clean_text(sample_text)

print(cleaned_sample[:2000])

Best Jira: Jira project management Course Online with Certification | GUVI LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Still Confused? Request a Callback Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Login Sign up Login Sign up LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Pre

### Remove exact repeated sentences/fragments

In [44]:
def remove_duplicate_segments(text):
    segments = re.split(r"(?<=[.!?])\s+", text)

    unique_segments = []
    seen = set()

    for segment in segments:
        segment = segment.strip()

        if segment and segment not in seen:
            unique_segments.append(segment)
            seen.add(segment)

    return " ".join(unique_segments)

In [45]:
cleaned_sample = clean_text(sample_text)
cleaned_sample = remove_duplicate_segments(cleaned_sample)

print(cleaned_sample[:2000])

Best Jira: Jira project management Course Online with Certification | GUVI LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Still Confused? Request a Callback Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Login Sign up Login Sign up LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Pre

### Apply cleaning to all 5 test pages

In [46]:
test_df["clean_content"] = test_df["content"].apply(clean_text)

In [47]:
test_df.columns

Index(['url', 'title', 'category', 'content', 'clean_content'], dtype='object')

In [48]:
test_df["raw_length"] = test_df["content"].str.len()

test_df["clean_length"] = test_df["clean_content"].str.len()

In [49]:
test_df[
    [
        "category",
        "title",
        "raw_length",
        "clean_length"
    ]
]

,category,title,raw_length,clean_length
0,Course,Best Jira: Jira project management Course Onli...,11197,11195
1,Other,HCL GUVI | Learn to code in your native language,17337,17337
2,Other,Referral | HCL GUVI,5636,5632
3,Practice,HCL GUVI | Learn to code in your native language,9775,9758
4,Other,Referral | HCL GUVI,5636,5632

In [50]:
print(test_df.iloc[0]["clean_content"][:1500])

Best Jira: Jira project management Course Online with Certification | GUVI LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Still Confused? Request a Callback Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Login Sign up Login Sign up LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend dev

In [51]:
# Remove exact duplicate sentences/segments
def remove_duplicate_segments(text):
    segments = re.split(r"(?<=[.!?])\s+", text)

    unique_segments = []
    seen = set()

    for segment in segments:
        segment = segment.strip()

        if segment and segment not in seen:
            unique_segments.append(segment)
            seen.add(segment)

    return " ".join(unique_segments)

In [52]:
test_df["clean_content"] = test_df["clean_content"].apply(
    remove_duplicate_segments
)

In [53]:
print(test_df.iloc[0]["clean_content"][:1500])

Best Jira: Jira project management Course Online with Certification | GUVI LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Still Confused? Request a Callback Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Login Sign up Login Sign up LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend dev

In [54]:
# Check missing values

test_df[
    ["url", "title", "category", "clean_content"]
].isnull().sum()

url              0
title            0
category         0
clean_content    0
dtype: int64

In [55]:
# Check for duplicate pages

print("Duplicate URLs:", test_df["url"].duplicated().sum())

Duplicate URLs: 0

In [56]:
print(
    "Duplicate Content:",
    test_df["clean_content"].duplicated().sum()
)

Duplicate Content: 1

### Create the final scraping function

In [57]:
def scrape_guvi_page(url):
    try:
        response = requests.get(
            url,
            timeout=10
        )

        if response.status_code != 200:
            print(f"Skipped: {url} - Status {response.status_code}")
            return None

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # Remove unnecessary HTML elements
        for tag in soup(["script", "style", "noscript"]):
            tag.decompose()

        # Extract page title
        title = (
            soup.title.get_text(strip=True)
            if soup.title
            else ""
        )

        # Extract page text
        content = soup.get_text(
            separator=" ",
            strip=True
        )

        # Clean the text
        content = clean_text(content)

        # Ignore pages with very little content
        if len(content) < 200:
            return None

        return {
            "url": url,
            "title": title,
            "category": get_category(url),
            "content": content
        }

    except requests.RequestException as error:
        print(f"Error: {url}")
        print(error)
        return None

In [58]:
# Test this final function on one known page

test_result = scrape_guvi_page(
    "https://www.guvi.in/faq/"
)

In [59]:
print("Title:")
print(test_result["title"])

print("\nCategory:")
print(test_result["category"])

print("\nContent Length:")
print(len(test_result["content"]))

Title:
FAQ | HCL GUVI

Category:
FAQ

Content Length:
10029

In [60]:
print(test_result["content"][:1000])

FAQ | HCL GUVI LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Still Confused? Request a Callback Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Logi

### Scrape all currently filtered GUVI links

In [61]:
all_data = []

for i, link in enumerate(filtered_links, start=1):

    print(f"Scraping {i}/{len(filtered_links)}")

    result = scrape_guvi_page(link)

    if result:
        all_data.append(result)

Scraping 1/50
Scraping 2/50
Scraping 3/50
Scraping 4/50
Scraping 5/50
Scraping 6/50
Scraping 7/50
Scraping 8/50
Scraping 9/50
Scraping 10/50
Error: https://www.guvi.in/webkata/
HTTPSConnectionPool(host='www.guvi.in', port=443): Read timed out. (read timeout=10)
Scraping 11/50
Scraping 12/50
Scraping 13/50
Scraping 14/50
Scraping 15/50
Scraping 16/50
Scraping 17/50
Scraping 18/50
Scraping 19/50
Scraping 20/50
Scraping 21/50
Scraping 22/50
Scraping 23/50
Scraping 24/50
Scraping 25/50
Scraping 26/50
Scraping 27/50
Scraping 28/50
Scraping 29/50
Scraping 30/50
Scraping 31/50
Scraping 32/50
Scraping 33/50
Scraping 34/50
Scraping 35/50
Scraping 36/50
Scraping 37/50
Scraping 38/50
Scraping 39/50
Scraping 40/50
Scraping 41/50
Scraping 42/50
Skipped: https://www.guvi.in/free-resources/  - Status 404
Scraping 43/50
Scraping 44/50
Scraping 45/50
Scraping 46/50
Scraping 47/50
Scraping 48/50
Scraping 49/50
Scraping 50/50

In [62]:
# Convert it into a DataFrame

guvi_df = pd.DataFrame(all_data)

In [63]:
print("Total URLs attempted:", len(filtered_links))
print("Successfully scraped:", len(guvi_df))

Total URLs attempted: 50
Successfully scraped: 47

In [64]:
# Check the first few rows

guvi_df[
    ["category", "title", "url"]
].head(10)

,category,title,url
0,Course,Best Jira: Jira project management Course Onli...,https://www.guvi.in/courses/project-management...
1,Other,HCL GUVI | Learn to code in your native language,https://www.guvi.in/
2,Other,Referral | HCL GUVI,https://www.guvi.in/referral/
3,Practice,HCL GUVI | Learn to code in your native language,https://www.guvi.in/code-kata/
4,Other,Referral | HCL GUVI,https://www.guvi.in/referral
5,Live Program,Zen Class - Career Programs from HCL GUVI,https://www.guvi.in/zen-class/
6,Other,Rewards | HCL GUVI,https://www.guvi.in/rewards/
7,Course,Best Claude Code Course Online with Certificat...,https://www.guvi.in/courses/machine-learning-a...
8,Live Program,Zen Class - Career Programs from HCL GUVI,https://www.guvi.in/zen-class
9,Other,"Learn Anytime, Anywhere with the HCL GUVI App",https://app.guvi.in/

In [65]:
# Identify failed URLs

scraped_urls = set(guvi_df["url"])

failed_urls = [
    link for link in filtered_links
    if link not in scraped_urls
]

print("Failed URLs:", len(failed_urls))

for url in failed_urls:
    print(url)

Failed URLs: 3
https://www.guvi.in/webkata/
https://www.guvi.in/free-resume-builder/
https://www.guvi.in/free-resources/

In [66]:
# Check category distribution

guvi_df["category"].value_counts()

category
Course          20
Other           13
Live Program     4
Practice         2
Community        2
Resource         1
Assessment       1
Policy           1
FAQ              1
Contact          1
About            1
Name: count, dtype: int64

In [67]:
# Inspect the Other category

other_pages = guvi_df[
    guvi_df["category"] == "Other"
][["title", "url"]]

other_pages

,title,url
1,HCL GUVI | Learn to code in your native language,https://www.guvi.in/
2,Referral | HCL GUVI,https://www.guvi.in/referral/
4,Referral | HCL GUVI,https://www.guvi.in/referral
6,Rewards | HCL GUVI,https://www.guvi.in/rewards/
9,"Learn Anytime, Anywhere with the HCL GUVI App",https://app.guvi.in/
10,Leader Board | HCL GUVI,https://www.guvi.in/leader-board/
12,Explore All GUVI Courses | Learn Coding in Eng...,https://www.guvi.in/explore-all-courses/
13,Join Our Affiliate Program & Earn Referral Com...,https://www.guvi.in/guvi-affiliate/
14,FixTheCode | HCL GUVI,https://www.guvi.in/debugging/
19,Learn Hub | Free Programming Guides & Tutorial...,https://www.guvi.in/hub/
25,"HCL GUVI For Corporates: Tailored Training, Hi...",https://www.guvi.in/corporates/
32,Rewards | HCL GUVI,https://www.guvi.in/rewards
34,IDE | HCL GUVI,https://www.guvi.in/ide/

In [68]:
# Normalize trailing slashes

def normalize_url(url):
    url = url.rstrip("/")
    return url

In [69]:
guvi_df["normalized_url"] = guvi_df["url"].apply(
    normalize_url
)

In [70]:
print(
    "Duplicate normalized URLs:",
    guvi_df["normalized_url"].duplicated().sum()
)

Duplicate normalized URLs: 3

In [71]:
guvi_df[
    guvi_df["normalized_url"].duplicated(
        keep=False
    )
][["title", "url", "normalized_url"]]

,title,url,normalized_url
2,Referral | HCL GUVI,https://www.guvi.in/referral/,https://www.guvi.in/referral
4,Referral | HCL GUVI,https://www.guvi.in/referral,https://www.guvi.in/referral
5,Zen Class - Career Programs from HCL GUVI,https://www.guvi.in/zen-class/,https://www.guvi.in/zen-class
6,Rewards | HCL GUVI,https://www.guvi.in/rewards/,https://www.guvi.in/rewards
8,Zen Class - Career Programs from HCL GUVI,https://www.guvi.in/zen-class,https://www.guvi.in/zen-class
32,Rewards | HCL GUVI,https://www.guvi.in/rewards,https://www.guvi.in/rewards

### Remove duplicate pages safely

In [72]:
guvi_df = guvi_df.drop_duplicates(
    subset="normalized_url",
    keep="first"
).reset_index(drop=True)

In [73]:
print("Total pages after removing duplicates:", len(guvi_df))

print(
    "Duplicate normalized URLs:",
    guvi_df["normalized_url"].duplicated().sum()
)

Total pages after removing duplicates: 44
Duplicate normalized URLs: 0

In [74]:
# Check missing values again after deduplication

guvi_df[
    ["url", "title", "category", "content"]
].isnull().sum()

url         0
title       0
category    0
content     0
dtype: int64

In [75]:
for column in ["url", "title", "category", "content"]:
    empty_count = (guvi_df[column].str.strip() == "").sum()
    print(f"{column}: {empty_count} empty values")

url: 0 empty values
title: 0 empty values
category: 0 empty values
content: 0 empty values

### Create the final cleaned dataset

In [76]:
final_df = guvi_df[
    [
        "normalized_url",
        "title",
        "category",
        "content"
    ]
].copy()

In [77]:
final_df = final_df.rename(
    columns={
        "normalized_url": "url"
    }
)

In [78]:
print("Final Dataset Shape:", final_df.shape)

final_df.head()

Final Dataset Shape: (44, 4)

,url,title,category,content
0,https://www.guvi.in/courses/project-management...,Best Jira: Jira project management Course Onli...,Course,Best Jira: Jira project management Course Onli...
1,https://www.guvi.in,HCL GUVI | Learn to code in your native language,Other,HCL GUVI | Learn to code in your native langua...
2,https://www.guvi.in/referral,Referral | HCL GUVI,Other,Referral | HCL GUVI Home LIVE Classes VLSI Des...
3,https://www.guvi.in/code-kata,HCL GUVI | Learn to code in your native language,Practice,HCL GUVI | Learn to code in your native langua...
4,https://www.guvi.in/zen-class,Zen Class - Career Programs from HCL GUVI,Live Program,Zen Class - Career Programs from HCL GUVI LIVE...

### Save the dataset

In [79]:
final_df.to_csv(
    "../data/guvi_raw_data.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!

In [80]:
check_df = pd.read_csv(
    "../data/guvi_raw_data.csv"
)

print("Saved Dataset Shape:", check_df.shape)
check_df.head()

Saved Dataset Shape: (44, 4)

,url,title,category,content
0,https://www.guvi.in/courses/project-management...,Best Jira: Jira project management Course Onli...,Course,Best Jira: Jira project management Course Onli...
1,https://www.guvi.in,HCL GUVI | Learn to code in your native language,Other,HCL GUVI | Learn to code in your native langua...
2,https://www.guvi.in/referral,Referral | HCL GUVI,Other,Referral | HCL GUVI Home LIVE Classes VLSI Des...
3,https://www.guvi.in/code-kata,HCL GUVI | Learn to code in your native language,Practice,HCL GUVI | Learn to code in your native langua...
4,https://www.guvi.in/zen-class,Zen Class - Career Programs from HCL GUVI,Live Program,Zen Class - Career Programs from HCL GUVI LIVE...

In [81]:
final_df.to_csv(
    "../data/guvi_raw_data.csv",
    index=False
)

In [82]:
check_df = pd.read_csv(
    "../data/guvi_raw_data.csv"
)

print(check_df.shape)

(44, 4)

In [83]:
import requests
import re

from bs4 import BeautifulSoup

In [84]:
def clean_text(text):
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s+([.,!?;:])", r"\1", text)
    text = text.strip()

    return text

In [85]:
def get_category(url):
    url = url.lower()

    if "/courses/" in url:
        return "Course"
    elif "/zen-class" in url:
        return "Live Program"
    elif "/faq" in url:
        return "FAQ"
    elif "/free-resources" in url:
        return "Resource"
    elif "/community/" in url:
        return "Community"
    elif "/code-kata" in url:
        return "Practice"
    elif "/webkata" in url:
        return "Practice"
    elif "/sqlkata" in url:
        return "Practice"
    elif "/skill-assessment" in url:
        return "Assessment"
    elif "/refund-policy" in url:
        return "Policy"
    elif "/about" in url:
        return "About"
    elif "/contact" in url:
        return "Contact"
    else:
        return "Other"

In [86]:
def scrape_guvi_page(url):
    try:
        response = requests.get(
            url,
            timeout=10
        )

        if response.status_code != 200:
            print(f"Skipped: {url} - Status {response.status_code}")
            return None

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # Remove unnecessary HTML elements
        for tag in soup(["script", "style", "noscript"]):
            tag.decompose()

        # Extract page title
        title = (
            soup.title.get_text(strip=True)
            if soup.title
            else ""
        )

        # Extract page content
        content = soup.get_text(
            separator=" ",
            strip=True
        )

        # Clean content
        content = clean_text(content)

        # Skip pages with very little content
        if len(content) < 200:
            return None

        return {
            "url": url,
            "title": title,
            "category": get_category(url),
            "content": content
        }

    except requests.RequestException as error:
        print(f"Error: {url}")
        print(error)
        return None

In [87]:
data_science_url = "https://www.guvi.in/zen-class/data-science-course/"

result = scrape_guvi_page(data_science_url)

if result:
    print("Title:", result["title"])
    print("Category:", result["category"])
    print("Content Length:", len(result["content"]))
else:
    print("Page could not be scraped")

Title: Data Science Course With Placement | Zen Class | HCL GUVI
Category: Live Program
Content Length: 27688

In [88]:
import pandas as pd
new_row = pd.DataFrame([result])

final_df = pd.concat(
    [final_df, new_row],
    ignore_index=True
)

In [89]:
print("Updated Dataset Shape:", final_df.shape)

Updated Dataset Shape: (45, 4)

In [90]:
final_df[
    final_df["title"].str.contains(
        "Data Science",
        case=False,
        na=False
    )
][["title", "category", "url"]]

,title,category,url
44,Data Science Course With Placement | Zen Class...,Live Program,https://www.guvi.in/zen-class/data-science-cou...

In [91]:
final_df.to_csv(
    "../data/guvi_raw_data.csv",
    index=False
)

print("Updated raw dataset saved!")
print("Shape:", final_df.shape)

Updated raw dataset saved!
Shape: (45, 4)

In [92]:
courses_url = (
    "https://www.guvi.in/explore-all-courses/"
    "?topic=web-development&sort=popularity"
)

courses_page = scrape_guvi_page(courses_url)

print("Title:", courses_page["title"])
print("Category:", courses_page["category"])
print("Content Length:", len(courses_page["content"]))
print()
print(courses_page["content"][:1500])

Title: Explore All GUVI Courses | Learn Coding in English, Hindi, Tamil & More
Category: Other
Content Length: 5754

Explore All GUVI Courses | Learn Coding in English, Hindi, Tamil & More LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Still Confused? Request a Callback Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Login Sign up Login Sign up LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend develo

In [93]:
print(courses_page["content"])

Explore All GUVI Courses | Learn Coding in English, Hindi, Tamil & More LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Still Confused? Request a Callback Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Login Sign up Login Sign up LIVE Classes VLSI Design Programme New IIT Delhi certified AI & Machine Learning New Intel & IIT-M Pravartak certified Data Science IIT-M Pravartak certified Full Stack Development IIT-M Pravartak certified UI/UX Design HCL GUVI certified AI DevOps Program HCL GUVI certified Explore all Programs Courses Practice CodeKata Sharpen your coding skills, prepare for interviews WebKata Build basic frontend & backend development skills SQLKata Master SQL concepts in relational database management FixTheCode A series of programs curated by industry experts IDE - Online Compiler Run & test your code in any programming language Resources Free Resources Referral Success Stories Blogs Learn Hub Get The App Rewards Become an Affiliate Leaderboard What's New? Resume Builder Community Hub Our Products HackerKID Coding classes platform for K-12 children GUVI For Corporates Meet your Hiring & Training Needs Placement Preparation Ace Up your Aptitude Still Confused? Request a Callback Welcome LIVE Classes Courses Practice Platforms Leaderboard Rewards Referral Profile Finish Welcome LIVE Classes Courses Practice Platforms Leaderboard Rewards Referral Profile Finish ✕ Welcome to HCL GUVI Hey there! Welcome to HCL GUVI—Grab Your Vernacular Imprint—where tech learning is easy, fun, and curated specially for you. Incubated by IIT Madras & IIM Ahmedabad in 2014 and now part of HCL Group, we're making quality tech education accessible to all. Join 3M+ learners breaking barriers and upskilling for a brighter future. We're here to guide you every step of the way! 🚀 LIVE Classes Zen Classes are HCL GUVI's most refined and flagship product—live, expert-led tech programs for beginners and pros. With IITM Pravartak affiliations, master Full-Stack, Data Science, DevOps, UI/UX, and more in multiple languages! Explore More Courses Looking for flexibility? HCL GUVI's 200+ self-paced courses let you learn anytime, anywhere! From free lessons to IIT-M & Autodesk-certified programs, gain in-demand skills in your preferred language. Explore More Practice Platforms Enhance your coding skills with HCL GUVI's Practice Platforms—interactive, structured, and designed to help you master programming effortlessly. CodeKata: A structured coding practice platform with 1500+ coding problems designed by industry experts. Ideal for beginners and professionals preparing for tech interviews with real-world coding challenges. Try Now > WebKata: An interactive platform to master HTML, CSS, JavaScript, and Bootstrap with a live coding environment. Perfect for hands-on web development practice without any setup. Try Now > SQLKata: A practice ground for mastering SQL queries used in real-world applications. Write, optimize, and refine your queries to build strong database skills. Try Now > FixTheCode: Hone your bug-fixing skills with real-world debugging challenges in Python, C++, JavaScript, and Golang. More languages coming soon! Try Now > IDE: A free online compiler supporting 20+ programming languages with auto-complete, debugging, and AI-powered code generation—all in the cloud! Try Now > Leaderboard Climb the leaderboard as you earn Geekoins by learning and practicing! The top scorers get featured, making learning competitive and rewarding. Keep going—you could be next! Explore More Rewards Earn Geekoins by watching videos and practicing problems, then redeem them for exciting rewards. The more you engage, the more you win! Explore More Referral Love learning with HCL GUVI? Share it with friends! Invite them using your unique link or code and unlock exciting rewards—Amazon vouchers, iPhones, and more. A Win-Win. Explore More Profile Your HCL GUVI profile is your digital portfolio! Track progress, showcase skills, add projects, and build a resume. Keep it updated—opportunities await! Explore More That's It! You Are Ready! You're all set to dive into your learning journey with HCL GUVI. Explore, upskill, and make each step count—exciting possibilities awaits! close Thank you for Reaching us out Our team will reach you out within the next 24 hours. Explore all Programs ✕ Home Explore Sort by Filter by Topic Language Rating Price Duration Course Type Sort by - Popularity English 4.0 Struts 6 Hrs 3.9k+ Enrolled ₹1,499 Tamil 4.0 Codeigniter in Tamil 6 Hrs 2k+ Enrolled ₹1,499 Tamil 4.2 PHP 5 Hrs 5.0k+ Enrolled ₹1,499 English 4.4 HTML & CSS 17 Hrs 20.0k+ Enrolled ₹1,999 English 5.0 Mastering jQuery 13 Hrs 2k+ Enrolled ₹3,499 Tamil 4.2 HTML & CSS in Tamil 12 Hrs 2k+ Enrolled ₹1,999 English 4.5 NodeJS 15 Hrs 2.4k+ Enrolled ₹3,499 English 4.6 Bootstrap 11 Hrs 2k+ Enrolled ₹3,499 Tamil 4.1 React.js in Tamil 6 Hrs 2k+ Enrolled ₹1,499 View more courses

In [94]:
courses_page["category"] = "Course"

existing_urls = final_df["url"].tolist()

if courses_page["url"] not in existing_urls:
    final_df = pd.concat(
        [
            final_df,
            pd.DataFrame([courses_page])
        ],
        ignore_index=True
    )

print("Updated Dataset Shape:", final_df.shape)

print(
    final_df[
        final_df["url"].str.contains(
            "explore-all-courses",
            case=False,
            na=False
        )
    ][["title", "category", "url"]]
)

Updated Dataset Shape: (46, 4)
                                                title category  \
10  Explore All GUVI Courses | Learn Coding in Eng...    Other
45  Explore All GUVI Courses | Learn Coding in Eng...   Course

                                                  url
10            https://www.guvi.in/explore-all-courses
45  https://www.guvi.in/explore-all-courses/?topic...

In [95]:
courses_page["category"] = "Course"

In [96]:
base_courses_url = "https://www.guvi.in/explore-all-courses"

# Remove both old/new versions
final_df = final_df[
    ~final_df["url"].str.contains(
        "explore-all-courses",
        case=False,
        na=False
    )
].reset_index(drop=True)

# Keep one clean course catalog row
courses_page["url"] = base_courses_url
courses_page["category"] = "Course"

final_df = pd.concat(
    [
        final_df,
        pd.DataFrame([courses_page])
    ],
    ignore_index=True
)

print("Updated Dataset Shape:", final_df.shape)

print(
    final_df[
        final_df["url"].str.contains(
            "explore-all-courses",
            case=False,
            na=False
        )
    ][["title", "category", "url"]]
)

Updated Dataset Shape: (45, 4)
                                                title category  \
44  Explore All GUVI Courses | Learn Coding in Eng...   Course

                                        url
44  https://www.guvi.in/explore-all-courses

In [97]:
final_df.to_csv(
    "../data/guvi_raw_data.csv",
    index=False
)

print("Saved successfully!")
print("Final Shape:", final_df.shape)

Saved successfully!
Final Shape: (45, 4)